services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Netresearch\NrXliffStreaming\:
    resource: '../Classes/*'

  # Make parser publicly available for dependency injection
  Netresearch\NrXliffStreaming\Parser\XliffStreamingParser:
    public: true
